### ISSUE TITLE
[v1.1.4 regression] Boot crash: readSettingString is not a function

### ISSUE THREAD

**Issue by SJY0917032** [GreenSheep01201/claw-empire#29]
## Summary
After updating to v1.1.4, server startup can crash during route initialization with:

```
TypeError: readSettingString is not a function
  at readAutoUpdateEnabledSetting (.../server/modules/routes/core.ts:498:29)
```

## Impact
- Claw-Empire process exits during startup
- Auto-update runtime toggle path cannot initialize

## Reproduction
1. Run v1.1.4 (`2bca327`) with default startup (`pnpm start`)
2. During route registration, auto-update state init calls `readAutoUpdateEnabledSetting()`
3. Crash occurs before server is fully ready

## Observed Trace (excerpt)
```
TypeError: readSettingString is not a function
    at readAutoUpdateEnabledSetting (.../server/modules/routes/core.ts:498:29)
    at refreshAutoUpdateActiveState (.../server/modules/routes/core.ts:508:22)
    at registerRoutesPartA (.../server/modules/routes/core.ts:823:5)
    at registerApiRoutes (.../server/modules/routes.ts:14:26)
    at .../server/server-main.ts:1757:31
```

## Root Cause
`core.ts` expects `__ctx.readSettingString`, but `server-main.ts` runtime context wiring does not provide `readSettingString`.

## Proposed Fix
Wire `readSettingString` into runtime context in `server-main.ts` (same pattern as other shared route helpers).

## Notes
A local hotfix confirms startup recovery once `readSettingString` is injected into runtime context.
